"use client";

import { useState, useEffect, use } from "react";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  ExternalLink,
  Clock,
  Shield,
  AlertTriangle,
  CheckCircle,
  Info,
  Download,
  ChevronDown,
  ChevronUp,
  Cpu,
} from "lucide-react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import ChatAssistant from "@/components/ChatAssistant";
import { jsPDF } from "jspdf";

interface Vulnerability {
  id: string;
  name: string;
  description: string;
  severity: "critical" | "high" | "medium" | "low" | "info";
  category: string;
  remediation: string;
  ai_explanation: string;
}

interface ScanDetail {
  id: string;
  target_url: string;
  security_score: number;
  status: string;
  scan_duration_ms: number;
  headers_checked: Record<string, string>;
  technologies: string[];
  created_at: string;
}

function ScoreToColor(score: number): string {
  if (score >= 90) return "#00e676";
  if (score >= 70) return "#ffc400";
  return "#ff1744";
}

const severityOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

export default function ScanDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [scan, setScan] = useState<ScanDetail | null>(null);
  const [vulnerabilities, setVulnerabilities] = useState<Vulnerability[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedVuln, setExpandedVuln] = useState<string | null>(null);
  const supabase = createClient();

  useEffect(() => {
    const fetchScanDetail = async () => {
      const { data: scanData } = await supabase
        .from("scans")
        .select("*")
        .eq("id", id)
        .single();

      if (scanData) {
        setScan(scanData);

        const { data: vulnData } = await supabase
          .from("vulnerabilities")
          .select("*")
          .eq("scan_id", id)
          .order("severity");

        if (vulnData) setVulnerabilities(vulnData);
      }

      setLoading(false);
    };

    fetchScanDetail();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const generateTextReport = () => {
    if (!scan) return;

    let report = `BugHunter AI — Security Scan Report\n`;
    report += `${"=".repeat(50)}\n\n`;
    report += `Target: ${scan.target_url}\n`;
    report += `Date: ${new Date(scan.created_at).toLocaleString()}\n`;
    report += `Security Score: ${scan.security_score}/100\n`;
    report += `Duration: ${(scan.scan_duration_ms / 1000).toFixed(1)}s\n`;
    report += `\n${"=".repeat(50)}\n\n`;
    report += `VULNERABILITIES (${vulnerabilities.length})\n\n`;

    vulnerabilities
      .sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity])
      .forEach((v, i) => {
        report += `${i + 1}. [${v.severity.toUpperCase()}] ${v.name}\n`;
        report += `   ${v.description}\n`;
        report += `   Fix: ${v.remediation}\n\n`;
      });

    report += `\n${"=".repeat(50)}\n`;
    report += `Generated by BugHunter AI\n`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bughunter-report-${scan.id.slice(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generatePDFReport = () => {
    if (!scan) return;
    const doc = new jsPDF();

    // Theme colors
    const primaryColor = [13, 21, 39]; // #0d1527 dark background

    // Cover Title Block
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 45, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("BugHunter AI Scan Report", 15, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated on ${new Date(scan.created_at).toLocaleString()}`, 15, 30);
    doc.text(`Target URL: ${scan.target_url}`, 15, 36);

    // Score Badge
    const score = scan.security_score;
    let scoreColor = [0, 230, 118]; // green
    if (score < 90 && score >= 70) scoreColor = [255, 196, 0]; // yellow/amber
    if (score < 70) scoreColor = [255, 23, 68]; // red

    doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.roundedRect(165, 12, 30, 20, 3, 3, "F");
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(String(score), 180, 22, { align: "center" });
    doc.setFontSize(8);
    doc.text("SECURITY SCORE", 180, 28, { align: "center" });

    // Section: Scan Information
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text("Scan Summary", 15, 58);

    doc.setDrawColor(230, 230, 230);
    doc.line(15, 62, 195, 62);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Scan Duration: ${(scan.scan_duration_ms / 1000).toFixed(1)} seconds`, 15, 70);
    doc.text(`Vulnerabilities Found: ${vulnerabilities.length}`, 15, 76);
    doc.text(`Technologies Detected: ${scan.technologies ? scan.technologies.join(", ") : "None detected"}`, 15, 82);

    // Section: Vulnerabilities Detail
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Detailed Vulnerability Findings", 15, 96);
    doc.line(15, 100, 195, 100);

    let yPosition = 110;
    const pageHeight = 297; // A4 height in mm

    if (vulnerabilities.length === 0) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(100, 100, 100);
      doc.text("No security vulnerabilities were identified on this website.", 15, yPosition);
    } else {
      vulnerabilities
        .sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity])
        .forEach((vuln, index) => {
          // Check if we need a new page
          if (yPosition > pageHeight - 60) {
            doc.addPage();
            yPosition = 20;
          }

          // Severity Color Indicator
          let sevColor = [0, 230, 118]; // green
          if (vuln.severity === "critical" || vuln.severity === "high") sevColor = [255, 23, 68];
          if (vuln.severity === "medium") sevColor = [255, 196, 0];

          // Left border accent bar for vulnerability
          doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
          doc.rect(15, yPosition, 2, 28, "F");

          // Vulnerability header
          doc.setFont("helvetica", "bold");
          doc.setFontSize(11);
          doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
          doc.text(`${index + 1}. ${vuln.name}`, 20, yPosition + 4);

          // Severity badge on right
          doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
          doc.roundedRect(165, yPosition, 30, 6, 1, 1, "F");
          doc.setFontSize(8);
          doc.setTextColor(255, 255, 255);
          doc.text(vuln.severity.toUpperCase(), 180, yPosition + 4, { align: "center" });

          // Description & Remediation text (with wrap)
          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.setTextColor(80, 80, 80);
          
          const descLines = doc.splitTextToSize(`Description: ${vuln.description}`, 170);
          const remediLines = doc.splitTextToSize(`Remediation: ${vuln.remediation}`, 170);
          
          doc.text(descLines, 20, yPosition + 11);
          const descHeight = descLines.length * 4.5;
          
          doc.setTextColor(40, 120, 80);
          doc.text(remediLines, 20, yPosition + 12 + descHeight);
          const remediHeight = remediLines.length * 4.5;

          yPosition += 16 + descHeight + remediHeight + 10;
        });
    }

    doc.save(`bughunter-report-${scan.id.slice(0, 8)}.pdf`);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="w-8 h-8 border-2 border-accent-cyan/30 border-t-accent-cyan rounded-full animate-spin" />
      </div>
    );
  }

  if (!scan) {
    return (
      <div className="text-center py-20">
        <Shield className="w-12 h-12 text-text-muted mx-auto mb-4" />
        <h2 className="text-xl font-bold mb-2">Scan Not Found</h2>
        <p className="text-text-secondary mb-6">
          This scan may have been deleted or doesn&apos;t exist
        </p>
        <Link
          href="/history"
          className="btn-primary inline-flex items-center gap-2"
        >
          <ArrowLeft className="w-4 h-4" /> Back to History
        </Link>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-4xl mx-auto space-y-6"
    >
      {/* Back Button */}
      <Link
        href="/history"
        className="inline-flex items-center gap-2 text-text-secondary hover:text-text-primary transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to History
      </Link>

      {/* Scan Header */}
      <div className="glass-card p-8">
        <div className="flex flex-col md:flex-row items-center gap-8">
          {/* Score Gauge */}
          <div className="score-gauge flex-shrink-0">
            <svg width="160" height="160" viewBox="0 0 160 160">
              <circle
                cx="80"
                cy="80"
                r="68"
                fill="none"
                stroke="rgba(148,163,184,0.1)"
                strokeWidth="10"
              />
              <circle
                cx="80"
                cy="80"
                r="68"
                fill="none"
                stroke={ScoreToColor(scan.security_score)}
                strokeWidth="10"
                strokeLinecap="round"
                strokeDasharray={`${2 * Math.PI * 68 * (scan.security_score / 100)} ${2 * Math.PI * 68}`}
                style={{
                  transform: "rotate(-90deg)",
                  transformOrigin: "center",
                }}
              />
            </svg>
            <span className="score-value text-3xl">{scan.security_score}</span>
            <span className="score-label">Score</span>
          </div>

          <div className="flex-1 text-center md:text-left">
            <h1 className="text-xl font-bold mb-2 flex items-center gap-2 justify-center md:justify-start">
              <ExternalLink className="w-5 h-5 text-text-muted" />
              {scan.target_url}
            </h1>
            <div className="flex flex-wrap gap-3 text-sm text-text-secondary justify-center md:justify-start">
              <span className="flex items-center gap-1.5">
                <Clock className="w-3.5 h-3.5" />
                {new Date(scan.created_at).toLocaleString()}
              </span>
              <span>
                Duration: {(scan.scan_duration_ms / 1000).toFixed(1)}s
              </span>
              <span>{vulnerabilities.length} issues found</span>
            </div>

            {/* Severity Summary */}
            <div className="flex flex-wrap gap-2 mt-4 justify-center md:justify-start">
              {(["critical", "high", "medium", "low", "info"] as const).map(
                (sev) => {
                  const count = vulnerabilities.filter(
                    (v) => v.severity === sev
                  ).length;
                  if (count === 0) return null;
                  return (
                    <span key={sev} className={`badge badge-${sev}`}>
                      {count} {sev}
                    </span>
                  );
                }
              )}
            </div>

            {/* Technologies */}
            {scan.technologies && scan.technologies.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-4 justify-center md:justify-start">
                {scan.technologies.map((tech, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-bg-secondary text-text-secondary text-xs border border-border"
                  >
                    <Cpu className="w-3 h-3" />
                    {tech}
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button
          onClick={generatePDFReport}
          className="btn-primary flex items-center gap-2 cursor-pointer"
        >
          <Download className="w-4 h-4" /> Download PDF Report
        </button>
        <button
          onClick={generateTextReport}
          className="btn-secondary flex items-center gap-2 cursor-pointer"
        >
          <Download className="w-4 h-4" /> Download Text Report
        </button>
      </div>

      {/* Vulnerabilities */}
      <div className="glass-card overflow-hidden">
        <div className="p-6 border-b border-border">
          <h2 className="text-lg font-semibold">Vulnerabilities</h2>
        </div>

        {vulnerabilities.length === 0 ? (
          <div className="p-12 text-center">
            <CheckCircle className="w-12 h-12 text-severity-low mx-auto mb-4" />
            <h3 className="text-lg font-medium">
              No Vulnerabilities Found!
            </h3>
            <p className="text-text-secondary mt-2">
              This site passed all security checks.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-border">
            {vulnerabilities
              .sort(
                (a, b) =>
                  severityOrder[a.severity] - severityOrder[b.severity]
              )
              .map((vuln) => {
                const isExpanded = expandedVuln === vuln.id;
                const Icon =
                  vuln.severity === "low" || vuln.severity === "info"
                    ? vuln.severity === "low"
                      ? CheckCircle
                      : Info
                    : AlertTriangle;

                return (
                  <div key={vuln.id}>
                    <button
                      onClick={() =>
                        setExpandedVuln(isExpanded ? null : vuln.id)
                      }
                      className="w-full p-5 flex items-center gap-4 text-left hover:bg-white/[0.01] transition-colors"
                    >
                      <Icon
                        className="w-5 h-5 flex-shrink-0"
                        style={{
                          color: `var(--color-severity-${vuln.severity})`,
                        }}
                      />
                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium">{vuln.name}</h3>
                        <p className="text-sm text-text-secondary truncate">
                          {vuln.description}
                        </p>
                      </div>
                      <span className={`badge badge-${vuln.severity}`}>
                        {vuln.severity}
                      </span>
                      {isExpanded ? (
                        <ChevronUp className="w-4 h-4 text-text-muted" />
                      ) : (
                        <ChevronDown className="w-4 h-4 text-text-muted" />
                      )}
                    </button>

                    {isExpanded && (
                      <div className="px-5 pb-5 pl-14 space-y-4">
                        <div className="p-4 rounded-xl bg-bg-secondary">
                          <h4 className="text-sm font-semibold text-accent-cyan mb-2">
                            📝 Description
                          </h4>
                          <p className="text-sm text-text-secondary leading-relaxed">
                            {vuln.description}
                          </p>
                        </div>
                        <div className="p-4 rounded-xl bg-bg-secondary">
                          <h4 className="text-sm font-semibold text-severity-low mb-2">
                            🔧 Remediation
                          </h4>
                          <p className="text-sm text-text-secondary leading-relaxed">
                            {vuln.remediation}
                          </p>
                        </div>
                        {vuln.ai_explanation && (
                          <div className="p-4 rounded-xl bg-accent-purple/5 border border-accent-purple/15">
                            <h4 className="text-sm font-semibold text-accent-purple mb-2">
                              🤖 AI Analysis
                            </h4>
                            <p className="text-sm text-text-secondary leading-relaxed">
                              {vuln.ai_explanation}
                            </p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                );
              })}
          </div>
        )}
      </div>
      {scan && (
        <ChatAssistant scanId={scan.id} targetUrl={scan.target_url} />
      )}
    </motion.div>
  );
}
